map: "warehouse"
world: "empty"
rviz_file: "view_multi.rviz"

robots_config:
  - robot1_type: "turtlebot3_waffle"
    robot1_global_planner: "lazy"
    robot1_local_planner: "orca"
    robot1_x_pos: "1.0"
    robot1_y_pos: "1.0"
    robot1_z_pos: "0.0"
    robot1_yaw: "3.14"

  - robot2_type: "turtlebot3_waffle"
    robot2_global_planner: "lazy"
    robot2_local_planner: "orca"
    robot2_x_pos: "-1.0"
    robot2_y_pos: "1.0"
    robot2_z_pos: "0.0"
    robot2_yaw: "-1.57"

  - robot3_type: "turtlebot3_waffle"
    robot3_global_planner: "lazy"
    robot3_local_planner: "orca"
    robot3_x_pos: "-1.0"
    robot3_y_pos: "-1.0"
    robot3_z_pos: "0.0"
    robot3_yaw: "0.0"

  - robot4_type: "turtlebot3_waffle"
    robot4_global_planner: "lazy"
    robot4_local_planner: "orca"
    robot4_x_pos: "1.0"
    robot4_y_pos: "-1.0"
    robot4_z_pos: "0.0"
    robot4_yaw: "1.57"

plugins:
  # pedestrians: "pedestrian_config.yaml"
  # obstacles: "obstacles_config.yaml"
  map_layers: "map_layers_config.yaml"
