SfmPlanner:
  # goal reached tolerance
  goal_dist_tolerance: 0.2
  rotate_tolerance: 0.5

  # linear velocity
  max_v: 0.5
  min_v: 0.0
  max_v_inc: 0.5

  # angular velocity
  max_w: 1.57
  min_w: 0.0
  max_w_inc: 1.57

  # frame id
  base_frame: base_link
  map_frame: map

  # sfm parameters
  radius: 0.2
  agent_max_velocity: 0.5
  agent_goal_weight: 2.0
  agent_obstacle_weight: 10.0
  agent_sigma_obstacle: 0.2
  agent_social_weight: 2.1
