shutdown_costmaps: false

planner_frequency: 0.1
planner_patience: 5.0

controller_frequency: 10
controller_patience: 1534

oscillation_timeout: 10.0
oscillation_distance: 0.2

conservative_reset_dist: 3.0
